version: '3'

services:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    ports:
      - 8088:8080

  rankme:
    image: catalysm/csgo-rankme:latest
    build: .
    command: npx nodemon
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_TABLE: ${MYSQL_TABLE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
